/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssignmentWhereUniqueInput } from "../../assignment/base/AssignmentWhereUniqueInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { AssignmentCreateNestedManyWithoutAgentsInput } from "./AssignmentCreateNestedManyWithoutAgentsInput";
import { PropertyCreateNestedManyWithoutAgentsInput } from "./PropertyCreateNestedManyWithoutAgentsInput";

@InputType()
class AgentCreateInput {
  @ApiProperty({
    required: false,
    type: () => AssignmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AssignmentWhereUniqueInput)
  @IsOptional()
  @Field(() => AssignmentWhereUniqueInput, {
    nullable: true,
  })
  assignment?: AssignmentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AssignmentCreateNestedManyWithoutAgentsInput,
  })
  @ValidateNested()
  @Type(() => AssignmentCreateNestedManyWithoutAgentsInput)
  @IsOptional()
  @Field(() => AssignmentCreateNestedManyWithoutAgentsInput, {
    nullable: true,
  })
  assignments?: AssignmentCreateNestedManyWithoutAgentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: () => PropertyCreateNestedManyWithoutAgentsInput,
  })
  @ValidateNested()
  @Type(() => PropertyCreateNestedManyWithoutAgentsInput)
  @IsOptional()
  @Field(() => PropertyCreateNestedManyWithoutAgentsInput, {
    nullable: true,
  })
  properties?: PropertyCreateNestedManyWithoutAgentsInput;
}

export { AgentCreateInput as AgentCreateInput };
